name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python ortamı kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Bağımlılıkları kur
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Testleri çalıştır
      run: |
        pytest test_app.py

    - name: Docker image oluştur
      run: |
        docker build -t flashhello-app .

    # Not: DockerHub push işlemi istersen bir sonraki adımda ekleyeceğiz
